package routes

import (
	"xdfc-server/authz"
	"xdfc-server/handlers"
	"xdfc-server/middleware"

	"github.com/gin-gonic/gin"
)

func registerTradingRoutes(authorized *gin.RouterGroup) {
	tradingAccess := middleware.RequireAnyPermission(authz.MenuTrading)
	purchaseAccess := middleware.RequireAnyPermission(authz.MenuPurchase)
	salesOrderManage := middleware.RequireAnyPermission(authz.ActionTradingSalesOrderManage)
	salesOrderDelete := middleware.RequireAnyPermission(authz.ActionTradingSalesOrderDelete)
	salesOrderSync := middleware.RequireAnyPermission(authz.ActionTradingSalesOrderSync)
	warehouseInboundRecord := middleware.RequireAnyPermission(authz.ActionWarehouseInboundRecord)
	customerManage := middleware.RequireAnyPermission(authz.ActionTradingCustomerManage)
	customerDelete := middleware.RequireAnyPermission(authz.ActionTradingCustomerDelete)
	customerSync := middleware.RequireAnyPermission(authz.ActionTradingCustomerSync)
	supplierManage := middleware.RequireAnyPermission(authz.ActionTradingSupplierManage)
	supplierDelete := middleware.RequireAnyPermission(authz.ActionTradingSupplierDelete)
	supplierSync := middleware.RequireAnyPermission(authz.ActionTradingSupplierSync)
	purchaseOrderManage := middleware.RequireAnyPermission(authz.ActionTradingPurchaseOrderManage)
	purchaseOrderDelete := middleware.RequireAnyPermission(authz.ActionTradingPurchaseOrderDelete)

	salesGroup := authorized.Group("/sales-orders")
	salesGroup.Use(tradingAccess)
	salesGroup.GET("", handlers.GetSalesOrdersHandler)
	salesGroup.GET("/analytics/customer-product-stats", handlers.GetSalesOrderCustomerProductStatsHandler)
	salesGroup.GET("/analytics/global-product-ranking", handlers.GetSalesOrderGlobalProductRankingHandler)
	salesGroup.POST("/after-sales-summary", handlers.GetSalesOrderAfterSalesSummaryHandler)
	salesGroup.GET("/:id", handlers.GetSalesOrderHandler)
	salesGroup.GET("/by-no/:orderNo", handlers.GetSalesOrderByNoHandler)
	salesGroup.POST("", salesOrderManage, handlers.SaveSalesOrderHandler)
	salesGroup.POST("/:id/returns", salesOrderManage, handlers.CreateSalesReturnHandler)
	salesGroup.POST("/:id/exchanges", salesOrderManage, handlers.CreateSalesExchangeHandler)
	salesGroup.POST("/:id/transactions", salesOrderManage, handlers.ExecuteSalesOrderTransactionHandler)
	salesGroup.PATCH("/:id", salesOrderManage, handlers.PatchSalesOrderHandler)
	salesGroup.DELETE("/:id", salesOrderDelete, handlers.DeleteSalesOrderHandler)
	salesGroup.POST("/sync", salesOrderSync, handlers.BulkSyncSalesOrdersHandler)
	salesGroup.POST("/evidence/upload", handlers.HandleEvidenceUpload)

	salesReturnGroup := authorized.Group("/sales-returns")
	salesReturnGroup.Use(tradingAccess)
	salesReturnGroup.GET("", handlers.GetSalesReturnsHandler)
	salesReturnGroup.GET("/:id", handlers.GetSalesReturnHandler)
	salesReturnGroup.GET("/:id/actual-amount-records", handlers.GetSalesReturnActualAmountRecordsHandler)
	salesReturnGroup.PATCH("/:id", salesOrderManage, handlers.PatchSalesReturnHandler)
	salesReturnGroup.PATCH("/:id/actual-amount", salesOrderManage, handlers.PatchSalesReturnActualAmountEntryHandler)
	salesReturnGroup.PATCH("/:id/logistics", salesOrderManage, handlers.PatchSalesReturnLogisticsHandler)
	salesReturnGroup.DELETE("/:id", salesOrderDelete, handlers.DeleteSalesReturnHandler)

	salesExchangeGroup := authorized.Group("/sales-exchanges")
	salesExchangeGroup.Use(tradingAccess)
	salesExchangeGroup.GET("", handlers.GetSalesExchangesHandler)
	salesExchangeGroup.GET("/:id", handlers.GetSalesExchangeHandler)
	salesExchangeGroup.POST("/:id/old-item-inbound", warehouseInboundRecord, handlers.ConfirmSalesExchangeOldItemInboundHandler)
	salesExchangeGroup.DELETE("/:id", salesOrderDelete, handlers.DeleteSalesExchangeHandler)

	customerGroup := authorized.Group("/customers")
	customerGroup.Use(tradingAccess)
	customerGroup.GET("", handlers.GetCustomersHandler)
	customerGroup.GET("/sales-closure-summary", handlers.GetCustomerSalesClosureSummaryHandler)
	customerGroup.GET("/sales-return-summary", handlers.GetCustomerSalesReturnSummaryHandler)
	customerGroup.POST("", customerManage, handlers.SaveCustomerHandler)
	customerGroup.POST("/:id/transactions", customerManage, handlers.ExecuteCustomerTransactionHandler)
	customerGroup.PATCH("/:id", customerManage, handlers.PatchCustomerHandler)
	customerGroup.DELETE("/:id", customerDelete, handlers.DeleteCustomerHandler)
	customerGroup.POST("/sync", customerSync, handlers.BulkSyncCustomersHandler)

	quoteGroup := authorized.Group("/quotes")
	quoteGroup.Use(tradingAccess)
	quoteGroup.GET("", handlers.GetQuotesHandler)
	quoteGroup.GET("/customer-summary", handlers.GetCustomerQuoteSummaryHandler)
	quoteGroup.GET("/:id", handlers.GetQuoteDetailHandler)
	quoteGroup.PATCH("/:id", salesOrderManage, handlers.PatchQuoteHandler)
	quoteGroup.POST("/:id/convert", salesOrderManage, handlers.ConvertQuoteHandler)

	supplierGroup := authorized.Group("/suppliers")
	supplierGroup.Use(purchaseAccess)
	supplierGroup.GET("", handlers.GetSuppliersHandler)
	supplierGroup.POST("", supplierManage, handlers.SaveSupplierHandler)
	supplierGroup.POST("/:id/transactions", supplierManage, handlers.ExecuteSupplierTransactionHandler)
	supplierGroup.PATCH("/:id", supplierManage, handlers.PatchSupplierHandler)
	supplierGroup.DELETE("/:id", supplierDelete, handlers.DeleteSupplierHandler)
	supplierGroup.POST("/sync", supplierSync, handlers.BulkSyncSuppliersHandler)

	purchaseGroup := authorized.Group("/purchase")
	purchaseGroup.Use(purchaseAccess)
	purchaseGroup.GET("/orders", handlers.GetPurchaseOrdersHandler)
	purchaseGroup.GET("/deleted-orders", handlers.GetDeletedPurchaseOrdersHandler)
	purchaseGroup.GET("/returns", handlers.GetPurchaseReturnsHandler)
	purchaseGroup.GET("/return-dictionaries", handlers.GetPurchaseReturnDictionariesHandler)
	purchaseGroup.GET("/orders/:id", handlers.GetPurchaseOrderHandler)
	purchaseGroup.POST("/orders", purchaseOrderManage, handlers.SavePurchaseOrderHandler)
	purchaseGroup.POST("/orders/:id/transactions", purchaseOrderManage, handlers.ExecutePurchaseOrderTransactionHandler)
	purchaseGroup.PATCH("/orders/:id", purchaseOrderManage, handlers.PatchPurchaseOrderHandler)
	purchaseGroup.POST("/evidence/upload", purchaseOrderManage, handlers.HandleEvidenceUpload)
	purchaseGroup.POST("/orders/:id/confirm-receipt", purchaseOrderManage, handlers.ConfirmPurchaseReceiptHandler)
	purchaseGroup.POST("/orders/:id/returns", purchaseOrderManage, handlers.CreatePurchaseReturnHandler)
	purchaseGroup.DELETE("/orders/:id", purchaseOrderDelete, handlers.DeletePurchaseOrderHandler)

	mrpGroup := authorized.Group("/mrp")
	mrpGroup.Use(middleware.RequireAnyPermission(authz.MenuMrp))
	mrpGroup.GET("/requirements", handlers.GetMrpRequirementsHandler)
}
