export const headerFields = {
      sectionTitle: 'Core Contract Attributes',
      lockedMessage: 'The order has been locked',
      orderNo: 'System Order No.',
      orderNoPlaceholder: 'Auto generated by system',
      customer: 'Customer',
      customerPlaceholder: 'Select customer...',
      tradeMode: 'Trade Mode',
      category: 'Category',
      orderDateRequired: 'Please select an order date',
      deliveryDeadline: 'Delivery Deadline',
      barcode: 'Contract Barcode',
      barcodePlaceholder: 'Auto generated barcode',
    } as const
