import { forwardRef, useMemo } from 'react'
import { useLanguage } from '@/context/language-provider'
import { useAuthStore } from '@/stores/auth-store'
import type { SalesOrder, SalesOrderLine } from '../../data/schema'

interface SalesOrderPrintProps {
  order: SalesOrder
}

const copyByLocale = {
  'zh-CN': {
    headerCaption: '销售订单单据',
    title: '销售订单清单',
    documentNoLabel: '销售单号',
    printTime: '打印时间',
    customerName: '客户单位',
    orderDate: '下单日期',
    deliveryDate: '交期',
    paymentMethod: '支付方式',
    paymentTerm: '结算方式',
    purchaseOrderNo: '客户单号',
    currency: '币种',
    totalQuantity: '订单总件数',
    totalAmount: '订单金额',
    requirements: '订单要求',
    itemSectionTitle: '订单明细',
    itemSectionDescription: '本清单用于销售订单打印与部门流转，默认展示订单核心字段与行项目摘要。',
    lineNo: '行号',
    product: '产品',
    specification: '产品摘要 / 描述',
    quantity: '订购数量',
    delivered: '已发数量',
    remaining: '待发数量',
    route: '工艺 / 备注',
    attributeSpec: '技术规范SOP',
    attributeDrilling: '打孔绑定图纸',
    attributeLabeling: '贴标绑定图纸',
    none: '无',
    noLines: '暂无订单行数据',
    signaturePreparedBy: '制单',
    signatureDepartment: '部门确认',
    signatureReceiver: '流转签收',
    currentAccount: '当前账号',
    footerNote: '本单据为系统生成的销售订单打印件，用于内部流转与信息核对，实际执行以系统业务记录为准。',
    printEdition: '销售订单打印版',
  },
  'en-US': {
    headerCaption: 'Sales Order Document',
    title: 'Sales Order List',
    documentNoLabel: 'Sales Order No.',
    printTime: 'Printed At',
    customerName: 'Customer',
    orderDate: 'Order Date',
    deliveryDate: 'Delivery Date',
    paymentMethod: 'Payment Method',
    paymentTerm: 'Payment Term',
    purchaseOrderNo: 'Customer PO',
    currency: 'Currency',
    totalQuantity: 'Total Quantity',
    totalAmount: 'Order Amount',
    requirements: 'Requirements',
    itemSectionTitle: 'Order Lines',
    itemSectionDescription: 'This print document is intended for sales order circulation and paper handoff, showing the essential order fields and line summaries.',
    lineNo: 'Line',
    product: 'Product',
    specification: 'Product Summary / Description',
    quantity: 'Ordered Qty',
    delivered: 'Delivered Qty',
    remaining: 'Remaining Qty',
    route: 'Route / Note',
    attributeSpec: 'Technical SOP',
    attributeDrilling: 'Drilling Drawing',
    attributeLabeling: 'Labeling Drawing',
    none: 'None',
    noLines: 'No order lines',
    signaturePreparedBy: 'Prepared By',
    signatureDepartment: 'Department Review',
    signatureReceiver: 'Receiver',
    currentAccount: 'Current Account',
    footerNote: 'This document is generated by the system for sales order circulation and review. Operational execution should follow the system records.',
    printEdition: 'Sales Order Print',
  },
} as const

function formatDisplayDate(value?: string, locale?: string) {
  if (!value) return '--'
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return value

  return new Intl.DateTimeFormat(locale === 'zh-CN' ? 'zh-CN' : 'en-US', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  }).format(date)
}

function formatDisplayDateTime(value?: string, locale?: string) {
  if (!value) return '--'
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return value

  return new Intl.DateTimeFormat(locale === 'zh-CN' ? 'zh-CN' : 'en-US', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
  }).format(date)
}

function formatDisplayNumber(value?: number, locale?: string) {
  return new Intl.NumberFormat(locale === 'zh-CN' ? 'zh-CN' : 'en-US').format(value || 0)
}

function buildCurrentIdentity(user?: {
  username?: string
}) {
  if (!user) return undefined
  return user.username?.trim() || undefined
}

function buildLineTitle(line: SalesOrderLine) {
  return [
    line.productDisplayTitleSnapshot,
    line.productModel,
    line.productCode,
    line.description,
  ].find((item) => item?.trim()) || '--'
}

function buildLineSubtitle(line: SalesOrderLine) {
  return [line.productDisplaySubtitleSnapshot, line.specification, line.description]
    .find((item) => item?.trim()) || '--'
}

function buildLineRoute(line: SalesOrderLine) {
  return [line.route, line.note].filter((item) => item?.trim()).join(' / ') || '--'
}

function buildLineSpecSummary(line: SalesOrderLine) {
  return line.engineeringSpecNameSnapshot?.trim() || ''
}

function buildLineDrillingSummary(line: SalesOrderLine) {
  return line.drillingPlanNameSnapshot?.trim() || ''
}

function buildLineLabelingSummary(line: SalesOrderLine) {
  return line.labelingPlanNameSnapshot?.trim() || ''
}

export const SalesOrderPrint = forwardRef<HTMLDivElement, SalesOrderPrintProps>(
  ({ order }, ref) => {
    const { locale } = useLanguage()
    const user = useAuthStore((state) => state.user)
    const copy = locale === 'zh-CN' ? copyByLocale['zh-CN'] : copyByLocale['en-US']
    const currentIdentity = useMemo(() => buildCurrentIdentity(user || undefined), [user])
    const totalDeliveredQty = useMemo(
      () => order.lines.reduce((sum, line) => sum + (line.deliveredQty || 0), 0),
      [order.lines]
    )
    const totalRemainingQty = useMemo(
      () => order.lines.reduce((sum, line) => sum + Math.max((line.qty || 0) - (line.deliveredQty || 0), 0), 0),
      [order.lines]
    )

    return (
      <div ref={ref} className='sales-order-print-root bg-white text-black'>
        <style type='text/css'>
          {`
            @media print {
              @page {
                size: A4 portrait;
                margin: 8mm;
              }
              body {
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
              }
              .sales-order-print-avoid-break {
                break-inside: avoid;
                page-break-inside: avoid;
              }
            }
          `}
        </style>

        <div className='mx-auto min-h-[calc(297mm-16mm)] w-full bg-white px-6 py-5 text-[12px] leading-6 text-black'>
          <div className='border-b-2 border-black pb-4'>
            <div className='flex items-start justify-between gap-4'>
              <div>
                <div className='pt-1 text-[10px] font-semibold uppercase tracking-[0.35em] text-black/55'>
                  {copy.headerCaption}
                </div>
              </div>
              <div className='flex-1 pt-2 text-center'>
                <h1 className='text-2xl font-bold tracking-[0.22em]'>{copy.title}</h1>
              </div>
              <div className='min-w-[160px] border border-black px-3 py-2 text-right text-[11px] leading-5'>
                <div className='text-black/65'>{copy.documentNoLabel}</div>
                <div className='font-bold'>{order.orderNo || '--'}</div>
              </div>
            </div>
            <div className='mt-4 flex justify-between border-t border-dashed border-black/30 pt-3 text-[11px]'>
              <span>
                {copy.documentNoLabel}：{order.orderNo || '--'}
              </span>
              <span>
                {copy.printTime}：{formatDisplayDateTime(new Date().toISOString(), locale)}
              </span>
            </div>
          </div>

          <div className='mt-6 grid grid-cols-2 gap-x-8 gap-y-3 text-sm'>
            <div>
              <span className='font-bold'>{copy.customerName}：</span>
              {order.customerName || '--'}
            </div>
            <div>
              <span className='font-bold'>{copy.orderDate}：</span>
              {formatDisplayDate(order.orderDate, locale)}
            </div>
            <div>
              <span className='font-bold'>{copy.deliveryDate}：</span>
              {formatDisplayDate(order.deliveryDate, locale)}
            </div>
            <div>
              <span className='font-bold'>{copy.paymentMethod}：</span>
              {order.paymentMethodName || order.paymentMethod || '--'}
            </div>
            <div>
              <span className='font-bold'>{copy.paymentTerm}：</span>
              {order.paymentTermName || order.paymentTerm || '--'}
            </div>
            <div>
              <span className='font-bold'>{copy.purchaseOrderNo}：</span>
              {order.purchaseOrderNo || '--'}
            </div>
            <div>
              <span className='font-bold'>{copy.currency}：</span>
              {order.currency || '--'}
            </div>
            <div>
              <span className='font-bold'>{copy.totalQuantity}：</span>
              {formatDisplayNumber(order.quantity, locale)}
            </div>
            <div>
              <span className='font-bold'>{copy.totalAmount}：</span>
              {formatDisplayNumber(order.amount, locale)}
            </div>
            <div>
              <span className='font-bold'>{copy.delivered}：</span>
              {formatDisplayNumber(totalDeliveredQty, locale)}
            </div>
            <div>
              <span className='font-bold'>{copy.remaining}：</span>
              {formatDisplayNumber(totalRemainingQty, locale)}
            </div>
            <div className='col-span-2'>
              <span className='font-bold'>{copy.requirements}：</span>
              {order.requirements?.trim() || '--'}
            </div>
          </div>

          <section className='mt-8'>
            <div className='border-b border-black pb-2'>
              <h2 className='text-base font-bold tracking-[0.08em]'>{copy.itemSectionTitle}</h2>
              <p className='mt-1 text-[10px] leading-5 text-black/70'>{copy.itemSectionDescription}</p>
            </div>
            <div className='mt-4 overflow-hidden border border-black'>
              <table className='w-full border-collapse text-left text-[11px] leading-5'>
                <thead>
                  <tr className='bg-black/4'>
                    <th className='border-b border-r border-black px-2 py-2 text-center font-bold'>{copy.lineNo}</th>
                    <th className='border-b border-r border-black px-3 py-2 font-bold'>{copy.product}</th>
                    <th className='border-b border-r border-black px-3 py-2 font-bold'>{copy.specification}</th>
                    <th className='border-b border-r border-black px-3 py-2 text-right font-bold'>{copy.quantity}</th>
                    <th className='border-b border-r border-black px-3 py-2 text-right font-bold'>{copy.delivered}</th>
                    <th className='border-b border-r border-black px-3 py-2 text-right font-bold'>{copy.remaining}</th>
                    <th className='border-b border-black px-3 py-2 font-bold'>{copy.route}</th>
                  </tr>
                </thead>
                <tbody>
                  {order.lines.length > 0 ? (
                    order.lines.map((line) => {
                      const remainingQty = Math.max((line.qty || 0) - (line.deliveredQty || 0), 0)
                      const specSummary = buildLineSpecSummary(line) || copy.none
                      const drillingSummary = buildLineDrillingSummary(line) || copy.none
                      const labelingSummary = buildLineLabelingSummary(line) || copy.none

                      return (
                        <tr key={`${order.id}-${line.lineNo}`} className='sales-order-print-avoid-break align-top'>
                          <td className='border-b border-r border-black/70 px-2 py-2 text-center font-mono'>
                            {line.lineNo}
                          </td>
                          <td className='border-b border-r border-black/70 px-3 py-2'>
                            <div className='font-bold'>{buildLineTitle(line)}</div>
                            <div className='text-[10px] text-black/60'>
                              {line.productCode?.trim() || line.productId || '--'}
                            </div>
                          </td>
                          <td className='border-b border-r border-black/70 px-3 py-2'>
                            <div>{buildLineSubtitle(line)}</div>
                            <div className='mt-1 space-y-0.5 text-[10px] leading-4 text-black/70'>
                              <div>
                                <span className='font-bold'>{copy.attributeSpec}：</span>
                                {specSummary}
                              </div>
                              <div>
                                <span className='font-bold'>{copy.attributeDrilling}：</span>
                                {drillingSummary}
                              </div>
                              <div>
                                <span className='font-bold'>{copy.attributeLabeling}：</span>
                                {labelingSummary}
                              </div>
                            </div>
                            <div className='text-[10px] text-black/60'>{line.description?.trim() || '--'}</div>
                          </td>
                          <td className='border-b border-r border-black/70 px-3 py-2 text-right'>
                            {formatDisplayNumber(line.qty, locale)} {line.uom}
                          </td>
                          <td className='border-b border-r border-black/70 px-3 py-2 text-right'>
                            {formatDisplayNumber(line.deliveredQty, locale)} {line.uom}
                          </td>
                          <td className='border-b border-r border-black/70 px-3 py-2 text-right'>
                            {formatDisplayNumber(remainingQty, locale)} {line.uom}
                          </td>
                          <td className='border-b border-black/70 px-3 py-2'>
                            {buildLineRoute(line)}
                          </td>
                        </tr>
                      )
                    })
                  ) : (
                    <tr>
                      <td colSpan={7} className='px-4 py-10 text-center text-black/60'>
                        {copy.noLines}
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </section>

          <div className='mt-12 grid grid-cols-3 gap-6 border-t border-dashed border-black/40 pt-8 text-xs'>
            <div className='min-h-[24mm]'>
              <div>
                {copy.signaturePreparedBy}：{currentIdentity || '______________'}
              </div>
              <div className='mt-10 text-black/45'>日期：______________</div>
            </div>
            <div className='min-h-[24mm]'>
              <div>{copy.signatureDepartment}：______________</div>
              <div className='mt-10 text-black/45'>日期：______________</div>
            </div>
            <div className='min-h-[24mm]'>
              <div>{copy.signatureReceiver}：______________</div>
              <div className='mt-10 text-black/45'>日期：______________</div>
            </div>
          </div>

          <div className='mt-10 border-t border-dashed border-black/40 pt-3 text-[10px] leading-5 text-black/65'>
            <div className='flex items-start justify-between gap-4'>
              <span className='flex-1'>{copy.footerNote}</span>
              <span className='shrink-0'>{copy.printEdition}</span>
            </div>
          </div>
        </div>
      </div>
    )
  }
)

SalesOrderPrint.displayName = 'SalesOrderPrint'
