// This file is auto-generated by scripts/generate-permission-contract.mjs
// Source of truth: server/authz/permissions.go
// Do not edit manually.

export const BACKEND_PERMISSION_CONTRACT_IDS = [
  "menu_dashboard",
  "menu_warehouse",
  "menu_trading",
  "menu_org",
  "menu_engineering",
  "menu_quality",
  "menu_prod_config",
  "menu_piecework",
  "menu_equipment",
  "menu_system",
  "menu_settings",
  "menu_approval",
  "menu_pda",
  "user_view",
  "user_create",
  "user_edit",
  "user_delete",
  "user_invite",
  "perm_manage",
  "action_warehouse_inbound_record",
  "action_warehouse_shipment_record",
  "action_warehouse_shipment_commit",
  "action_warehouse_shipment_void",
  "action_warehouse_transfer",
  "action_warehouse_reconcile",
  "action_warehouse_sync",
  "action_warehouse_category_manage",
  "action_warehouse_stocktake_manage",
  "action_warehouse_adjustment_submit",
  "action_warehouse_adjustment_execute",
  "action_trading_sales_order_manage",
  "action_trading_sales_order_delete",
  "action_trading_sales_order_sync",
  "action_trading_customer_manage",
  "action_trading_customer_delete",
  "action_trading_customer_sync",
  "action_trading_supplier_manage",
  "action_trading_supplier_delete",
  "action_trading_supplier_sync",
  "action_trading_purchase_order_manage",
  "action_trading_purchase_order_delete",
  "action_trading_purchase_order_sync",
  "action_trading_logistics_manage",
  "action_trading_logistics_status_update",
  "action_trading_logistics_delete",
  "action_trading_logistics_provider_manage",
  "action_equipment_mold_manage",
  "action_equipment_mold_sync",
  "action_equipment_drawing_manage",
  "action_equipment_drawing_delete",
  "action_equipment_furnace_manage",
  "action_equipment_furnace_sync",
  "action_equipment_partner_manage",
  "action_equipment_loan_manage",
  "action_equipment_telemetry_update",
  "action_approval_config_manage",
  "action_approval_review"
] as const

export const BACKEND_ADMIN_FALLBACK_PERMISSION_IDS = [
  "user_view",
  "user_create",
  "user_edit",
  "user_delete",
  "perm_manage",
  "menu_dashboard",
  "menu_warehouse",
  "menu_trading",
  "menu_org",
  "menu_engineering",
  "menu_quality",
  "menu_prod_config",
  "menu_piecework",
  "menu_equipment",
  "menu_system",
  "menu_settings",
  "menu_approval",
  "action_warehouse_inbound_record",
  "action_warehouse_shipment_record",
  "action_warehouse_shipment_commit",
  "action_warehouse_shipment_void",
  "action_warehouse_transfer",
  "action_warehouse_reconcile",
  "action_warehouse_sync",
  "action_warehouse_category_manage",
  "action_warehouse_stocktake_manage",
  "action_warehouse_adjustment_submit",
  "action_warehouse_adjustment_execute",
  "action_trading_sales_order_manage",
  "action_trading_sales_order_delete",
  "action_trading_sales_order_sync",
  "action_trading_customer_manage",
  "action_trading_customer_delete",
  "action_trading_customer_sync",
  "action_trading_supplier_manage",
  "action_trading_supplier_delete",
  "action_trading_supplier_sync",
  "action_trading_purchase_order_manage",
  "action_trading_purchase_order_delete",
  "action_trading_purchase_order_sync",
  "action_trading_logistics_manage",
  "action_trading_logistics_status_update",
  "action_trading_logistics_delete",
  "action_trading_logistics_provider_manage",
  "action_equipment_mold_manage",
  "action_equipment_mold_sync",
  "action_equipment_drawing_manage",
  "action_equipment_drawing_delete",
  "action_equipment_furnace_manage",
  "action_equipment_furnace_sync",
  "action_equipment_partner_manage",
  "action_equipment_loan_manage",
  "action_equipment_telemetry_update",
  "action_approval_config_manage",
  "action_approval_review",
  "menu_pda"
] as const

const BACKEND_PERMISSION_CONTRACT_SET = new Set(BACKEND_PERMISSION_CONTRACT_IDS)
const BACKEND_MANAGED_PERMISSION_PREFIX = /^(menu_|action_|user_|perm_)/

function normalizePermissionId(permissionId: string): string {
  return permissionId.trim().toLowerCase()
}

/**
 * Assert frontend managed permission IDs stay aligned with backend source of truth.
 *
 * Rules:
 * 1. Backend-managed IDs must all exist in frontend permission registry.
 * 2. Frontend IDs that match managed prefixes cannot drift out of backend contract.
 */
export function assertBackendPermissionContract(permissionIds: string[]): void {
  const normalizedFrontendIds = new Set(
    permissionIds.map((permissionId) => normalizePermissionId(permissionId)).filter(Boolean),
  )

  const missingFromFrontend = BACKEND_PERMISSION_CONTRACT_IDS.filter(
    (permissionId) => !normalizedFrontendIds.has(permissionId),
  )

  const unexpectedManagedIds = Array.from(normalizedFrontendIds).filter(
    (permissionId) =>
      BACKEND_MANAGED_PERMISSION_PREFIX.test(permissionId) &&
      !BACKEND_PERMISSION_CONTRACT_SET.has(permissionId as (typeof BACKEND_PERMISSION_CONTRACT_IDS)[number]),
  )

  if (missingFromFrontend.length === 0 && unexpectedManagedIds.length === 0) {
    return
  }

  const diagnostics = []
  if (missingFromFrontend.length > 0) {
    diagnostics.push('missing=' + missingFromFrontend.join(','))
  }
  if (unexpectedManagedIds.length > 0) {
    diagnostics.push('unexpected=' + unexpectedManagedIds.join(','))
  }

  throw new Error('[permission-contract] Frontend/backend permission drift detected: ' + diagnostics.join(' | '))
}
