package services

// Legacy audit module constants kept here as the shared source of truth for now.
// Registry, alias, order, and stats responsibilities have been split into
// audit_registry.go, audit_alias.go, and audit_stats.go.
const (
	AuditModuleSalesOrder            = "sales-order"
	AuditModulePurchaseOrder         = "purchase-order"
	AuditModuleCustomer              = "customer"
	AuditModuleProduct               = "product"
	AuditModuleSupplier              = "supplier"
	AuditModuleDrilling              = "drilling"
	AuditModuleEngineeringSpec       = "engineering-spec"
	AuditModuleEmployee              = "employee"
	AuditModuleMaterial              = "material"
	AuditModuleInventory             = "inventory"
	AuditModuleShipment              = "shipment"
	AuditModuleLogistics             = "logistics"
	AuditModulePackagingAssembly     = "packaging-assembly"
	AuditModuleVehicleModelTemplate  = "vehicle-model-template"
	AuditModuleChangeOrder           = "change-order"
	AuditModuleBOM                   = "bom"
	AuditModuleUser                  = "user"
	AuditModuleUserPermission        = "user-permission"
	AuditModulePermissionPreset      = "permission-preset"
	AuditModuleProductionLine        = "production-line"
	AuditModuleProductionRoute       = "production-route"
	AuditModuleProductionOperation   = "production-operation"
	AuditModuleOutsourcePartner      = "outsource-partner"
	AuditModuleOutsourceOrder        = "outsource-order"
	AuditModuleCurrency              = "currency"
	AuditModulePaymentTerm           = "payment-term"
	AuditModulePaymentMethod         = "payment-method"
	AuditModuleTaxRate               = "tax-rate"
	AuditModuleExchangeRateConfig    = "exchange-rate-config"
	AuditModuleMold                  = "mold"
	AuditModuleFurnace               = "furnace"
	AuditModuleMaintenanceRecord     = "maintenance-record"
	AuditModuleMoldDrawing           = "mold-drawing"
	AuditModuleEquipmentPartner      = "equipment-partner"
	AuditModuleMoldLoan              = "mold-loan"
	AuditModuleStocktake             = "stocktake"
	AuditModulePieceworkRate         = "piecework-rate"
	AuditModuleTeam                  = "team"
	AuditModuleInspectionStandard    = "inspection-standard"
	AuditModuleInspectionTask        = "inspection-task"
	AuditModuleOrganization          = "organization"
	AuditModuleEnterpriseConfig      = "enterprise-config"
	AuditModuleCuttingEngineConfig   = "cutting-engine-config"
	AuditModuleApprovalRequest       = "approval-request"
	AuditModuleBusinessAnalysisQuery = "business-analysis-query"
)

const (
	AuditEngineModuleTrading          = "trading"
	AuditEngineModuleFinance          = "finance"
	AuditEngineModuleEquipment        = "equipment"
	AuditEngineModuleEngineering      = "engineering"
	AuditEngineModuleCuttingEngine    = "cutting-engine"
	AuditEngineModuleWarehouse        = "warehouse"
	AuditEngineModuleProduction       = "production"
	AuditEngineModuleQuality          = "quality"
	AuditEngineModuleOrganization     = "organization"
	AuditEngineModuleSystem           = "system"
	AuditEngineModuleWorkflow         = "workflow"
	AuditEngineModuleBusinessAnalysis = "business-analysis"
)
