import type { QueryKey } from '@tanstack/react-query'

export const warehouseQueryKeys = {
  all: (): QueryKey => ['warehouse'],
  inboundHistory: (): QueryKey => ['warehouse', 'inbound-history'],
  shipmentHistory: (): QueryKey => ['warehouse', 'shipment-history'],
  shipmentDemands: (): QueryKey => ['warehouse', 'shipment-demands'],
  inventoryBOMAlertDetails: (): QueryKey => ['warehouse', 'inventory-bom-alert-details'],
  thresholdRules: (): QueryKey => ['warehouse', 'threshold-rules'],
  thresholdTargetOptions: (): QueryKey => ['warehouse', 'threshold-target-options'],
  masterDataAll: (): QueryKey => ['warehouse', 'master-data', 'all'],
  masterDataSearch: (scope: string, query: string): QueryKey => [
    'warehouse',
    'master-data',
    'search',
    scope,
    query,
  ],
  inventoryBreakdown: (materialId: string): QueryKey => ['warehouse', 'inventory-breakdown', materialId],
  categoryStock: (materialId: string, category: string): QueryKey => ['warehouse', 'category-stock', materialId, category],
  stocktakeTasks: (): QueryKey => ['warehouse', 'stocktake-tasks'],
  stocktakeItems: (taskId: string): QueryKey => ['warehouse', 'stocktake-items', taskId],
  inventoryAdjustments: (): QueryKey => ['warehouse', 'inventory-adjustments'],
  packagingAssemblies: (): QueryKey => ['warehouse', 'packaging-assemblies'],
  categoryList: (): QueryKey => ['warehouse_categories'],
  categoryOptions: (): QueryKey => ['warehouse_category_options'],
  alertThresholds: (): QueryKey => ['inventory_thresholds'],
  inventoryList: (): QueryKey => ['inventory_list'],
  inventoryValuation: (): QueryKey => ['inventory_valuation'],
  inventoryAlertSummary: (): QueryKey => ['inventory_alert_summary'],
} as const
