[package]
name = "xdfc-vehicle-loading-engine-core"
version.workspace = true
edition.workspace = true

[lib]
name = "xdfc_vehicle_loading_engine_core"
path = "src/lib.rs"

[dependencies]
gltf = { version = "1.4.1", default-features = false, features = ["utils", "names", "extras"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lints]
workspace = true
