import { describe, expect, it } from 'vitest'
import type { BatchOptimizerPlan } from '../types'
import { resolveBatchEngineExplainabilityHighlightZoneIds } from './batch-engine-phase7-visualization'

function buildPlan(): BatchOptimizerPlan {
  return {
    rank: 1,
    strategyKey: 'phase7-geometry-priority-first',
    score: 98.2,
    utilizationPercent: 91.2,
    lossAreaM2: 0.012,
    explanation: 'phase7 explainability',
    assignments: [],
    unfulfilledLines: [],
    layoutSummary: {
      canvasWidthMm: 200,
      canvasHeightMm: 120,
      rollCount: 1,
      assignmentCount: 1,
      fulfilledDemandLineCount: 1,
      unfulfilledDemandLineCount: 0,
      rolls: [],
      demandLines: [],
      zones: [],
    },
    geometryLayoutSummary: {
      canvasWidthMm: 200,
      canvasHeightMm: 120,
      zones: [],
    },
    lossBreakdown: {
      unusedRollAreaM2: 0,
      unfulfilledAreaM2: 0,
      trimLossAreaM2: 0,
      message: '--',
    },
    comparisonSummary: {
      fulfilledDemandCount: 1,
      mustFulfillSatisfied: true,
      splitDemandCount: 0,
      usedRollCount: 1,
      usedRollPercent: 100,
      unusedRollAreaM2: 0,
      unfulfilledAreaM2: 0,
      trimLossAreaM2: 0,
    },
    scoreBreakdown: {
      objectivePreset: 'yield-first',
      appliedWeights: {
        fulfilledWeight: 35,
        utilizationWeight: 55,
        stabilityWeight: 10,
        assignmentPenaltyWeight: 4,
        unfulfilledPenaltyWeight: 12,
        splitPenaltyWeight: 6,
        mustPenaltyWeight: 45,
      },
      fulfilledRatePercent: 100,
      fulfilledContribution: 35,
      utilizationContribution: 55,
      stabilityContribution: 10,
      assignmentPenalty: 0,
      unfulfilledPenalty: 0,
      splitPenalty: 0,
      mustFulfillPenalty: 0,
      groupSplitCount: 0,
      sequenceViolationCount: 0,
      adjacencyBreakCount: 1,
      directionSwitchCount: 0,
      mixViolationCount: 0,
      rollSwitchCount: 1,
      geometryReuseHitCount: 2,
      reusableResidualAreaM2: 0.001,
      finalScore: 98.2,
    },
    mustFulfillDiagnostics: [],
    diffSummary: {
      baselinePlanRank: 1,
      baselineStrategyKey: 'phase7-geometry-priority-first',
      mode: 'baseline',
      addedZoneIds: [],
      removedZoneIds: [],
      changedDemandLineIds: [],
      changedRollIds: [],
      highlightZoneIds: [],
    },
    diffSummaries: [],
    searchConfig: {
      presetKey: 'yield-first',
      beamWidth: 8,
      maxSearchDepth: 6,
      perDemandBranchingLimit: 3,
      residualReuseBias: 2,
      convergenceAreaBucketM2: 0.001,
    },
    candidateBudgetSummary: {
      perStrategyQuota: 2,
      globalBudget: 4,
      mergedCandidateCount: 2,
      strategyStats: [],
      dynamicStrategyStats: [],
    },
    budgetRerankReason: 'fulfilled=4 / broken=1 / cluster=1 / reuse=2',
    explainabilitySummary: {
      groupSegments: [],
      sequenceSegments: [],
      adjacencySegments: [],
      primaryBreakReasons: ['组连续段被打断'],
      heatZoneAttributions: [],
      breakSlices: [
        {
          id: 'slice-1',
          segmentKind: 'group',
          segmentKey: 'grp-a',
          breakPosition: 1,
          breakBeforeDemandLineId: 'line-a',
          breakAfterDemandLineId: 'line-b',
          zoneIds: ['zone-a', 'zone-b'],
          clusterId: 'cluster-a',
          reason: '组连续段被打断',
          severityScore: 2.4,
        },
      ],
      zoneClusters: [
        {
          clusterId: 'cluster-a',
          zoneIds: ['zone-a', 'zone-b', 'zone-c'],
          rollIds: ['roll-1'],
          demandLineIds: ['line-a', 'line-b'],
          breakSliceIds: ['slice-1'],
          dominantReason: '组连续段被打断',
          dominantDemandLineId: 'line-b',
          densityScore: 3.2,
        },
      ],
    },
    reportSummary: {
      planRank: 1,
      strategyKey: 'phase7-geometry-priority-first',
      objectivePreset: 'yield-first',
      appliedWeights: {
        fulfilledWeight: 35,
        utilizationWeight: 55,
        stabilityWeight: 10,
        assignmentPenaltyWeight: 4,
        unfulfilledPenaltyWeight: 12,
        splitPenaltyWeight: 6,
        mustPenaltyWeight: 45,
      },
      baselinePlanRank: 1,
      baselineStrategyKey: 'phase7-geometry-priority-first',
      score: 98.2,
      utilizationPercent: 91.2,
      lossAreaM2: 0.012,
      mustFulfillRiskCount: 0,
      changedDemandLineCount: 0,
      changedRollCount: 0,
      highlightZoneCount: 0,
      adjacencyBreakCount: 1,
      rollSwitchCount: 1,
      geometryReuseHitCount: 2,
      reusableResidualAreaM2: 0.001,
      searchConfig: {
        presetKey: 'yield-first',
        beamWidth: 8,
        maxSearchDepth: 6,
        perDemandBranchingLimit: 3,
        residualReuseBias: 2,
        convergenceAreaBucketM2: 0.001,
      },
      candidateBudgetSummary: {
        perStrategyQuota: 2,
        globalBudget: 4,
        mergedCandidateCount: 2,
        strategyStats: [],
        dynamicStrategyStats: [],
      },
      budgetRerankReason: 'fulfilled=4 / broken=1 / cluster=1 / reuse=2',
      explainabilitySummary: {
        groupSegments: [],
        sequenceSegments: [],
        adjacencySegments: [],
        primaryBreakReasons: ['组连续段被打断'],
        heatZoneAttributions: [],
        breakSlices: [],
        zoneClusters: [],
      },
      comparisonSummary: {
        fulfilledDemandCount: 1,
        mustFulfillSatisfied: true,
        splitDemandCount: 0,
        usedRollCount: 1,
        usedRollPercent: 100,
        unusedRollAreaM2: 0,
        unfulfilledAreaM2: 0,
        trimLossAreaM2: 0,
      },
      scoreBreakdown: {
        objectivePreset: 'yield-first',
        appliedWeights: {
          fulfilledWeight: 35,
          utilizationWeight: 55,
          stabilityWeight: 10,
          assignmentPenaltyWeight: 4,
          unfulfilledPenaltyWeight: 12,
          splitPenaltyWeight: 6,
          mustPenaltyWeight: 45,
        },
        fulfilledRatePercent: 100,
        fulfilledContribution: 35,
        utilizationContribution: 55,
        stabilityContribution: 10,
        assignmentPenalty: 0,
        unfulfilledPenalty: 0,
        splitPenalty: 0,
        mustFulfillPenalty: 0,
        groupSplitCount: 0,
        sequenceViolationCount: 0,
        adjacencyBreakCount: 1,
        directionSwitchCount: 0,
        mixViolationCount: 0,
        rollSwitchCount: 1,
        geometryReuseHitCount: 2,
        reusableResidualAreaM2: 0.001,
        finalScore: 98.2,
      },
    },
  }
}

describe('resolveBatchEngineExplainabilityHighlightZoneIds', () => {
  it('returns linked zone ids for break slice target', () => {
    expect(resolveBatchEngineExplainabilityHighlightZoneIds(buildPlan(), 'slice-1', 'break-slice')).toEqual(['zone-a', 'zone-b'])
  })

  it('returns linked zone ids for zone cluster target', () => {
    expect(resolveBatchEngineExplainabilityHighlightZoneIds(buildPlan(), 'cluster-a', 'zone-cluster')).toEqual(['zone-a', 'zone-b', 'zone-c'])
  })

  it('returns empty array when target is missing', () => {
    expect(resolveBatchEngineExplainabilityHighlightZoneIds(buildPlan(), '', '')).toEqual([])
  })
})
