import { describe, expect, it } from 'vitest'
import { buildBatchEngineGeometryLayout } from './build-batch-engine-geometry-layout'
import type { BatchOptimizerPlan } from '../types'

function buildPlan(): BatchOptimizerPlan {
  return {
    rank: 1,
    strategyKey: 'phase1-geometry',
    score: 100,
    utilizationPercent: 88,
    lossAreaM2: 0.012,
    explanation: 'phase1 geometry',
    assignments: [],
    unfulfilledLines: [],
    layoutSummary: {
      canvasWidthMm: 200,
      canvasHeightMm: 200,
      rollCount: 1,
      assignmentCount: 1,
      fulfilledDemandLineCount: 1,
      unfulfilledDemandLineCount: 0,
      rolls: [],
      demandLines: [],
      zones: [],
    },
    geometryLayoutSummary: {
      canvasWidthMm: 200,
      canvasHeightMm: 200,
      zones: [
        {
          id: 'piece-1',
          kind: 'piece',
          usageCategory: 'piece',
          label: 'P1',
          detail: 'line-1 / 45°',
          rollId: 'roll-1',
          demandLineId: 'line-1',
          areaM2: 0.0016,
          allocatedSets: 0,
          allocatedPieces: 1,
          coverageSharePercent: 100,
          tooltipLines: ['需求行: line-1'],
          polygonPoints: [
            { x: 100, y: 20 },
            { x: 180, y: 100 },
            { x: 100, y: 180 },
            { x: 20, y: 100 },
          ],
        },
      ],
    },
    lossBreakdown: {
      unusedRollAreaM2: 0,
      unfulfilledAreaM2: 0,
      trimLossAreaM2: 0,
      message: '',
    },
    comparisonSummary: {
      fulfilledDemandCount: 1,
      mustFulfillSatisfied: true,
      splitDemandCount: 0,
      usedRollCount: 1,
      usedRollPercent: 100,
      unusedRollAreaM2: 0,
      unfulfilledAreaM2: 0,
      trimLossAreaM2: 0,
    },
    scoreBreakdown: {
      objectivePreset: 'yield-first',
      appliedWeights: {
        fulfilledWeight: 35,
        utilizationWeight: 55,
        stabilityWeight: 10,
        assignmentPenaltyWeight: 4,
        unfulfilledPenaltyWeight: 12,
        splitPenaltyWeight: 6,
        mustPenaltyWeight: 45,
      },
      fulfilledRatePercent: 100,
      fulfilledContribution: 35,
      utilizationContribution: 55,
      stabilityContribution: 10,
      assignmentPenalty: 0,
      unfulfilledPenalty: 0,
      splitPenalty: 0,
      mustFulfillPenalty: 0,
      groupSplitCount: 0,
      sequenceViolationCount: 0,
      adjacencyBreakCount: 0,
      directionSwitchCount: 0,
      mixViolationCount: 0,
      rollSwitchCount: 0,
      geometryReuseHitCount: 0,
      reusableResidualAreaM2: 0,
      finalScore: 100,
    },
    mustFulfillDiagnostics: [],
    diffSummary: {
      baselinePlanRank: 1,
      baselineStrategyKey: 'phase1-geometry',
      mode: 'baseline',
      addedZoneIds: [],
      removedZoneIds: [],
      changedDemandLineIds: [],
      changedRollIds: [],
      highlightZoneIds: [],
    },
    diffSummaries: [],
    searchConfig: {
      presetKey: 'default',
      beamWidth: 1,
      maxSearchDepth: 1,
      perDemandBranchingLimit: 1,
      residualReuseBias: 0,
      convergenceAreaBucketM2: 0,
    },
    candidateBudgetSummary: {
      perStrategyQuota: 1,
      globalBudget: 1,
      mergedCandidateCount: 1,
      strategyStats: [],
      dynamicStrategyStats: [],
    },
    budgetRerankReason: '',
    explainabilitySummary: {
      groupSegments: [],
      sequenceSegments: [],
      adjacencySegments: [],
      primaryBreakReasons: [],
      heatZoneAttributions: [],
      breakSlices: [],
      zoneClusters: [],
    },
    reportSummary: {
      planRank: 1,
      strategyKey: 'phase1-geometry',
      objectivePreset: 'yield-first',
      appliedWeights: {
        fulfilledWeight: 35,
        utilizationWeight: 55,
        stabilityWeight: 10,
        assignmentPenaltyWeight: 4,
        unfulfilledPenaltyWeight: 12,
        splitPenaltyWeight: 6,
        mustPenaltyWeight: 45,
      },
      baselinePlanRank: 1,
      baselineStrategyKey: 'phase1-geometry',
      score: 100,
      utilizationPercent: 88,
      lossAreaM2: 0.012,
      mustFulfillRiskCount: 0,
      changedDemandLineCount: 0,
      changedRollCount: 0,
      highlightZoneCount: 0,
      adjacencyBreakCount: 0,
      rollSwitchCount: 0,
      geometryReuseHitCount: 0,
      reusableResidualAreaM2: 0,
      searchConfig: {
        presetKey: 'default',
        beamWidth: 1,
        maxSearchDepth: 1,
        perDemandBranchingLimit: 1,
        residualReuseBias: 0,
        convergenceAreaBucketM2: 0,
      },
      candidateBudgetSummary: {
        perStrategyQuota: 1,
        globalBudget: 1,
        mergedCandidateCount: 1,
        strategyStats: [],
        dynamicStrategyStats: [],
      },
      budgetRerankReason: '',
      explainabilitySummary: {
        groupSegments: [],
        sequenceSegments: [],
        adjacencySegments: [],
        primaryBreakReasons: [],
        heatZoneAttributions: [],
        breakSlices: [],
        zoneClusters: [],
      },
      comparisonSummary: {
        fulfilledDemandCount: 1,
        mustFulfillSatisfied: true,
        splitDemandCount: 0,
        usedRollCount: 1,
        usedRollPercent: 100,
        unusedRollAreaM2: 0,
        unfulfilledAreaM2: 0,
        trimLossAreaM2: 0,
      },
      scoreBreakdown: {
        objectivePreset: 'yield-first',
        appliedWeights: {
          fulfilledWeight: 35,
          utilizationWeight: 55,
          stabilityWeight: 10,
          assignmentPenaltyWeight: 4,
          unfulfilledPenaltyWeight: 12,
          splitPenaltyWeight: 6,
          mustPenaltyWeight: 45,
        },
        fulfilledRatePercent: 100,
        fulfilledContribution: 35,
        utilizationContribution: 55,
        stabilityContribution: 10,
        assignmentPenalty: 0,
        unfulfilledPenalty: 0,
        splitPenalty: 0,
        mustFulfillPenalty: 0,
        groupSplitCount: 0,
        sequenceViolationCount: 0,
        adjacencyBreakCount: 0,
        directionSwitchCount: 0,
        mixViolationCount: 0,
        rollSwitchCount: 0,
        geometryReuseHitCount: 0,
        reusableResidualAreaM2: 0,
        finalScore: 100,
      },
    },
  }
}

describe('buildBatchEngineGeometryLayout', () => {
  it('maps geometry layout summary into polygon canvas zones', () => {
    const layout = buildBatchEngineGeometryLayout(buildPlan())

    expect(layout).not.toBeNull()
    expect(layout?.zones).toHaveLength(1)
    expect(layout?.zones[0]?.polygonPoints).toHaveLength(4)
    expect(layout?.zones[0]?.x).toBe(20)
    expect(layout?.zones[0]?.y).toBe(20)
    expect(layout?.zones[0]?.width).toBe(160)
    expect(layout?.zones[0]?.height).toBe(160)
  })
})
